### ISSUE TITLE
no_affinity ==> less number of cores

### ISSUE THREAD

**Issue by phirus2** [OpenMathLib/OpenBLAS#903] opened 2016-06-01 09:54 UTC
if I comment this option in the Makefile.rule my problem doesn't use the total of the cores available (128) it uses a lower number of cores. why???

To be sure... comment this option should force each thread to be binded in the same core. am I right

**Comment by jeromerobert** [comment] 2016-06-01 11:47
From https://github.com/xianyi/OpenBLAS/issues/900#issuecomment-222932852 you have 64 cores, not 128. I guess OpenBLAS is smart enough to bind on cores and not on cpu threads.

This option force each OpenBLAS thread to be bound to a core and avoid them moving from core to core.

**Comment by phirus2** [comment] 2016-06-01 12:53
I can execute 128 threads at the same time. so let's start to say that my machine has 128 ¿Virtual? CPU. If I execute with openMP I launch 128 threads. Yeah, I know that I have 64 "real" cores and 128 with Hyper-Threading. 

Anyway I still have my question. Why the number of cores used to solve the same problem decrease using the same openBlas library just commenting the variable at compile time??? 

The bind mask of the kernel has 128bits. one for each cpu-threads. Fix me if I wrong but the affinity option use this mask to bind the threads. 

I'm interested to bind each thread in each cpu threads or real core (the caches will be the same)

Thx for the quick answer

**Comment by brada4** [comment] 2016-06-01 18:36
Because hypperthread is half-speed half-cache cpu.
It cannot speed up anything

**Comment by phirus2** [comment] 2016-06-02 08:32
Ok. I don't care the performance for now. I just want know why commenting that option and using 128 threads them don't execute in all the core. They just execute in 80 cores. It's true that they don't switch in different cores. But it's like the mask of threads was shorter than necessary to cover  all available cores.

Here are htop with different number of cores and where are executing
128cores 
![htop-128](https://cloud.githubusercontent.com/assets/19668974/15738361/374d6974-28ab-11e6-8664-c96d01d73754.PNG)

96 cores
![htop-96](https://cloud.githubusercontent.com/assets/19668974/15738563/3acfd27a-28ac-11e6-80e2-908793af4b7e.PNG)

80 cores
![htop-80](https://cloud.githubusercontent.com/assets/19668974/15738562/3aad51e6-28ac-11e6-8c9f-8df11cb010ce.PNG)

64 cores
![htop-64](https://cloud.githubusercontent.com/assets/19668974/15738564/3ad68dae-28ac-11e6-8c8b-9c3024007d20.PNG)


Now I can see that commenting this option does not decrease the number of cores used (this is the right), the problem seems they are fixed to don't use all the available cores. What do you thing???

Thanks for your help

**Comment by jeromerobert** [comment] 2016-06-02 10:23
@phirus2 Sounds like a bug. May be you could try to remove this #ifdef:
https://github.com/xianyi/OpenBLAS/blob/develop/driver/others/init.c#L735
to get more diagnostics.

**Comment by phirus2** [comment] 2016-06-02 10:35
Ok. I'm using the release 18 and I have  commented the same code (line 802 and 804)

`Giving Affinity[  0] -->   0`

**Comment by phirus2** [comment] 2016-06-02 11:00
well I have commented another DEBUG lines in the numa_mapping functions. It seems tha the mistake comes from here:

```
From /sys ...
CPU ( 0) : 00000000
CPU ( 1) : 00010004
CPU ( 2) : 00020008
...
CPU (77) : 00110377
CPU (78) : 0012037b
CPU (79) : 0013037f

Sorting ...
CPU ( 0) : 00000000
CPU ( 1) : 00000101
CPU ( 2) : 00000202
....
CPU (77) : 0013017d
CPU (78) : 0013027e
CPU (79) : 0013037f
```
Just unti 80 core, where is the problem.
Also I have checked the common-> num_nodes and num_procs, are right: 4, 128. So the problem  I guess is in these lines:

```
  for (node = 0; node < common -> num_nodes; node ++) {
    core = 0;
    for (cpu = 0; cpu < common -> num_procs; cpu ++) {
      bitmask_idx = CPUELT(cpu);
      if (common -> node_info[node][bitmask_idx] & common -> avail[bitmask_idx] & CPUMASK(cpu)) {
        common -> cpu_info[count] = WRITE_CORE(core) | WRITE_NODE(node) | WRITE_CPU(cpu);
        count ++;
        core ++;
      }

    }
  }
```

**Comment by phirus2** [comment] 2016-06-02 13:17
I have included this printings to know what is happening at creation of common->node_info


```
#define BYTE_TO_BINARY_PATTERN "%c%c%c%c%c%c%c%c"
#define BYTE_TO_BINARY_VALUE(byte)                                      \
  (byte & 0x80 ? '1' : '0'), (byte & 0x40 ? '1' : '0'), (byte & 0x20 ? '1' : '0'), (byte & 0x10 ? '1' : '0'), \
    (byte & 0x08 ? '1' : '0'), (byte & 0x04 ? '1' : '0'), (byte & 0x02 ? '1' : '0'), (byte & 0x01 ? '1' : '0')
```

```
  while ((dir = readdir(dp)) != NULL) {
    if (strncmp(dir->d_name, "node", 4)==0) {
      node = atoi(&dir -> d_name[4]);
      if (node > MAX_NODES) {
        fprintf(stderr, "\nOpenBLAS Warning : MAX_NODES (NUMA) is too small. Terminated.\n");
        exit(1);
      }

      common -> num_nodes ++;
      get_cpumap(node, common->node_info[node]);
      fprintf (stderr, "node %d :\n", node);
      int k = 0;
      while (k < MAX_BITMASK_LEN) {
        fprintf (stderr, "  -%d [%020lu]==>", k, common->node_info[node][k]);
        j = 7;
        while (j >=0){
          fprintf (stderr, BYTE_TO_BINARY_PATTERN, BYTE_TO_BINARY_VALUE(common->node_info[node][k]>>j*8));
          j--;
        }
        fprintf (stderr, "\n");
        k++;
      }
    }
```


With this modifications the mask printed is:

```
node 0 :
  -0 [00000000000000004369]==>0000000000000000000000000000000000000000000000000001000100010001
  -1 [01229782938247303441]==>0001000100010001000100010001000100010001000100010001000100010001
  -2 [00000018764998447377]==>0000000000000000000100010001000100010001000100010001000100010001
  -3 [00000000000000000000]==>0000000000000000000000000000000000000000000000000000000000000000
node 1 :
  -0 [00000000000000008738]==>0000000000000000000000000000000000000000000000000010001000100010
  -1 [02459565876494606882]==>0010001000100010001000100010001000100010001000100010001000100010
  -2 [00000037529996894754]==>0000000000000000001000100010001000100010001000100010001000100010
  -3 [00000000000000000000]==>0000000000000000000000000000000000000000000000000000000000000000
node 2 :
  -0 [00000000000000017476]==>0000000000000000000000000000000000000000000000000100010001000100
  -1 [04919131752989213764]==>0100010001000100010001000100010001000100010001000100010001000100
  -2 [00000075059993789508]==>0000000000000000010001000100010001000100010001000100010001000100
  -3 [00000000000000000000]==>0000000000000000000000000000000000000000000000000000000000000000
node 3 :
  -0 [00000000000000034952]==>0000000000000000000000000000000000000000000000001000100010001000
  -1 [09838263505978427528]==>1000100010001000100010001000100010001000100010001000100010001000
  -2 [00000150119987579016]==>0000000000000000100010001000100010001000100010001000100010001000
  -3 [00000000000000000000]==>00000000000000000000000000000000000000000000000000000000000000
```

here is the definition of common structure:
```
typedef struct {
  unsigned long lock;
  unsigned int magic;
  unsigned int shmid;

  int num_nodes;
  int num_procs;
  int final_num_procs;
  unsigned long avail [MAX_BITMASK_LEN];
  int avail_count;
  unsigned long cpu_info   [MAX_CPUS];
  unsigned long long node_info  [MAX_NODES][MAX_BITMASK_LEN];
  int cpu_use[MAX_CPUS];
} shm_t;
```

The maximum number of bits of node_info is 64 bits. In this case with 128 maybe there is a problem

**Comment by phirus2** [comment] 2016-06-02 14:44
one question. Why don't use numa api'???

**Comment by brada4** [comment] 2016-06-02 20:02
Because it does not exist...

**Comment by brada4** [comment] 2016-06-02 23:11
You havr 8 10-core cpus. Either find kernel that handles 160 hyperthreads or disable hyperthreading to get under 128.

**Comment by jeromerobert** [comment] 2016-06-03 08:29
@phirus2 By NUMPA API you mean hwloc ?

**Comment by jeromerobert** [comment] 2016-06-03 08:37
@phirus2 May be replacing 8 by 16 here would be enougth:
https://github.com/xianyi/OpenBLAS/blob/develop/driver/others/init.c#L99

**Comment by phirus2** [comment] 2016-06-03 09:30
@jeromerobert I asked because to get the info of the hw (cores, caches) It is using files like for example '/sys/devices/system/node/node*/cpumap' and parsing it later. Looking about this files in google I have found this man page of num library http://linux.die.net/man/3/numa . It seems give tools to work in numa architectures (mask, number cores, affinity, caches,...)

I will try do that along the day when I got it I will let you know

**Comment by brada4** [comment] 2016-06-03 16:58
API or not but structure allocations happen outside BLAS which makes it close to impossible to guess right NUMA position for each call. Even worse there is cgroups (used by redhat numactl at least) that leaves no affinity trail in /proc

**Comment by martin-frbg** [comment] 2024-03-28 11:37
Closing as i cannot reproduce the enumeration error with any recent version - there have been several fixes to that part of the code starting from version 0.3.0, but unfortunately I did not have access to suitable hardware for testing this specific issue back then

**Closed by martin-frbg** 2024-03-28 11:37 UTC
